### ISSUE TITLE
Command injection

### ISSUE THREAD

**Issue by emillon** [UnixJunkie/lz4-chans#4]
Hi,

This library builds command strings based on the file names. It seems that they are not probably sanitized, which can lead to command injection. This can be shown in the following example:

```
% dune utop
utop # Lz4_chans.open_in_bin "$(firefox)";;
<firefox starts>
```

I recommend using a library like `bos` to build commands in a safe way. Thanks!

**Comment by UnixJunkie** [comment]
If you send a pull request, I will review it.
I might also merge it, if I like it.

**Comment by UnixJunkie** [comment]
Note that checking that the string passed is a valid unix filename should be enough to correct
this security problem, without introducing one more lib dependency.
This would be more likely to be merged.

**Comment by emillon** [comment]
Sorry, I'm not interested in writing a PR as I'm not using this library.

I saw your announce on discuss and had a quick look at how it works, so it's just a quick heads-up for your users :slightly_smiling_face:.

> checking that the string passed is a valid unix filename should be enough to correct
this security problem

No, unfortunately this doesn't work as `"$(firefox)"` or `"filename; command" are valid filenames too.

**Comment by UnixJunkie** [comment]
corrected in this commit: https://github.com/UnixJunkie/lz4-chans/commit/01028b38a013ae39105a385d1e399d194a57d4e3
Thanks for the heads up.
